"""Add product intelligence fields

Revision ID: bc76045f57ed
Revises: e032bd862116
Create Date: 2026-07-23 23:43:16.425657

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc76045f57ed'
down_revision: Union[str, Sequence[str], None] = 'e032bd862116'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('brand', sa.String(), nullable=True))
    op.add_column('products', sa.Column('category', sa.String(), nullable=True))
    op.add_column('products', sa.Column('barcode', sa.String(), nullable=True))
    op.add_column('products', sa.Column('market_price', sa.Float(), nullable=True))
    op.add_column('products', sa.Column('sales_velocity', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'sales_velocity')
    op.drop_column('products', 'market_price')
    op.drop_column('products', 'barcode')
    op.drop_column('products', 'category')
    op.drop_column('products', 'brand')
    # ### end Alembic commands ###
