"""add sales tracking

Revision ID: d647c72f162d
Revises: 2ece3e73a78b
Create Date: 2026-07-25 15:17:04.850985

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd647c72f162d'
down_revision: Union[str, Sequence[str], None] = '2ece3e73a78b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory', sa.Column('sale_price', sa.Float(), nullable=True))
    op.add_column('inventory', sa.Column('actual_profit', sa.Float(), nullable=True))
    op.add_column('inventory', sa.Column('actual_roi', sa.Float(), nullable=True))
    op.add_column('inventory', sa.Column('purchase_date', sa.DateTime(), nullable=True))
    op.add_column('inventory', sa.Column('sold_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inventory', 'sold_at')
    op.drop_column('inventory', 'purchase_date')
    op.drop_column('inventory', 'actual_roi')
    op.drop_column('inventory', 'actual_profit')
    op.drop_column('inventory', 'sale_price')
    # ### end Alembic commands ###
